// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3.proto

package remote;

public final class Service3 {
  private Service3() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeatingSystemRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeatingSystemRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string roomID = 1;</code>
     */
    java.lang.String getRoomID();
    /**
     * <code>string roomID = 1;</code>
     */
    com.google.protobuf.ByteString
        getRoomIDBytes();

    /**
     * <code>float desiredTemperature = 2;</code>
     */
    float getDesiredTemperature();
  }
  /**
   * Protobuf type {@code HeatingSystemRequest}
   */
  public  static final class HeatingSystemRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeatingSystemRequest)
      HeatingSystemRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeatingSystemRequest.newBuilder() to construct.
    private HeatingSystemRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeatingSystemRequest() {
      roomID_ = "";
      desiredTemperature_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeatingSystemRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              roomID_ = s;
              break;
            }
            case 21: {

              desiredTemperature_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return remote.Service3.internal_static_HeatingSystemRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return remote.Service3.internal_static_HeatingSystemRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              remote.Service3.HeatingSystemRequest.class, remote.Service3.HeatingSystemRequest.Builder.class);
    }

    public static final int ROOMID_FIELD_NUMBER = 1;
    private volatile java.lang.Object roomID_;
    /**
     * <code>string roomID = 1;</code>
     */
    public java.lang.String getRoomID() {
      java.lang.Object ref = roomID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomID_ = s;
        return s;
      }
    }
    /**
     * <code>string roomID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRoomIDBytes() {
      java.lang.Object ref = roomID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESIREDTEMPERATURE_FIELD_NUMBER = 2;
    private float desiredTemperature_;
    /**
     * <code>float desiredTemperature = 2;</code>
     */
    public float getDesiredTemperature() {
      return desiredTemperature_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRoomIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, roomID_);
      }
      if (desiredTemperature_ != 0F) {
        output.writeFloat(2, desiredTemperature_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRoomIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, roomID_);
      }
      if (desiredTemperature_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, desiredTemperature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof remote.Service3.HeatingSystemRequest)) {
        return super.equals(obj);
      }
      remote.Service3.HeatingSystemRequest other = (remote.Service3.HeatingSystemRequest) obj;

      boolean result = true;
      result = result && getRoomID()
          .equals(other.getRoomID());
      result = result && (
          java.lang.Float.floatToIntBits(getDesiredTemperature())
          == java.lang.Float.floatToIntBits(
              other.getDesiredTemperature()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROOMID_FIELD_NUMBER;
      hash = (53 * hash) + getRoomID().hashCode();
      hash = (37 * hash) + DESIREDTEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDesiredTemperature());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static remote.Service3.HeatingSystemRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static remote.Service3.HeatingSystemRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static remote.Service3.HeatingSystemRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static remote.Service3.HeatingSystemRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static remote.Service3.HeatingSystemRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static remote.Service3.HeatingSystemRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static remote.Service3.HeatingSystemRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static remote.Service3.HeatingSystemRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static remote.Service3.HeatingSystemRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static remote.Service3.HeatingSystemRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static remote.Service3.HeatingSystemRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static remote.Service3.HeatingSystemRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(remote.Service3.HeatingSystemRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeatingSystemRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeatingSystemRequest)
        remote.Service3.HeatingSystemRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return remote.Service3.internal_static_HeatingSystemRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return remote.Service3.internal_static_HeatingSystemRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                remote.Service3.HeatingSystemRequest.class, remote.Service3.HeatingSystemRequest.Builder.class);
      }

      // Construct using remote.Service3.HeatingSystemRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        roomID_ = "";

        desiredTemperature_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return remote.Service3.internal_static_HeatingSystemRequest_descriptor;
      }

      @java.lang.Override
      public remote.Service3.HeatingSystemRequest getDefaultInstanceForType() {
        return remote.Service3.HeatingSystemRequest.getDefaultInstance();
      }

      @java.lang.Override
      public remote.Service3.HeatingSystemRequest build() {
        remote.Service3.HeatingSystemRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public remote.Service3.HeatingSystemRequest buildPartial() {
        remote.Service3.HeatingSystemRequest result = new remote.Service3.HeatingSystemRequest(this);
        result.roomID_ = roomID_;
        result.desiredTemperature_ = desiredTemperature_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof remote.Service3.HeatingSystemRequest) {
          return mergeFrom((remote.Service3.HeatingSystemRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(remote.Service3.HeatingSystemRequest other) {
        if (other == remote.Service3.HeatingSystemRequest.getDefaultInstance()) return this;
        if (!other.getRoomID().isEmpty()) {
          roomID_ = other.roomID_;
          onChanged();
        }
        if (other.getDesiredTemperature() != 0F) {
          setDesiredTemperature(other.getDesiredTemperature());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        remote.Service3.HeatingSystemRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (remote.Service3.HeatingSystemRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object roomID_ = "";
      /**
       * <code>string roomID = 1;</code>
       */
      public java.lang.String getRoomID() {
        java.lang.Object ref = roomID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          roomID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string roomID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRoomIDBytes() {
        java.lang.Object ref = roomID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roomID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string roomID = 1;</code>
       */
      public Builder setRoomID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roomID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string roomID = 1;</code>
       */
      public Builder clearRoomID() {
        
        roomID_ = getDefaultInstance().getRoomID();
        onChanged();
        return this;
      }
      /**
       * <code>string roomID = 1;</code>
       */
      public Builder setRoomIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roomID_ = value;
        onChanged();
        return this;
      }

      private float desiredTemperature_ ;
      /**
       * <code>float desiredTemperature = 2;</code>
       */
      public float getDesiredTemperature() {
        return desiredTemperature_;
      }
      /**
       * <code>float desiredTemperature = 2;</code>
       */
      public Builder setDesiredTemperature(float value) {
        
        desiredTemperature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float desiredTemperature = 2;</code>
       */
      public Builder clearDesiredTemperature() {
        
        desiredTemperature_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HeatingSystemRequest)
    }

    // @@protoc_insertion_point(class_scope:HeatingSystemRequest)
    private static final remote.Service3.HeatingSystemRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new remote.Service3.HeatingSystemRequest();
    }

    public static remote.Service3.HeatingSystemRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeatingSystemRequest>
        PARSER = new com.google.protobuf.AbstractParser<HeatingSystemRequest>() {
      @java.lang.Override
      public HeatingSystemRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeatingSystemRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeatingSystemRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeatingSystemRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public remote.Service3.HeatingSystemRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AirflowRateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AirflowRateRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string roomID = 1;</code>
     */
    java.lang.String getRoomID();
    /**
     * <code>string roomID = 1;</code>
     */
    com.google.protobuf.ByteString
        getRoomIDBytes();

    /**
     * <code>float desiredAirflowRate = 2;</code>
     */
    float getDesiredAirflowRate();
  }
  /**
   * Protobuf type {@code AirflowRateRequest}
   */
  public  static final class AirflowRateRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AirflowRateRequest)
      AirflowRateRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AirflowRateRequest.newBuilder() to construct.
    private AirflowRateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AirflowRateRequest() {
      roomID_ = "";
      desiredAirflowRate_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AirflowRateRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              roomID_ = s;
              break;
            }
            case 21: {

              desiredAirflowRate_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return remote.Service3.internal_static_AirflowRateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return remote.Service3.internal_static_AirflowRateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              remote.Service3.AirflowRateRequest.class, remote.Service3.AirflowRateRequest.Builder.class);
    }

    public static final int ROOMID_FIELD_NUMBER = 1;
    private volatile java.lang.Object roomID_;
    /**
     * <code>string roomID = 1;</code>
     */
    public java.lang.String getRoomID() {
      java.lang.Object ref = roomID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomID_ = s;
        return s;
      }
    }
    /**
     * <code>string roomID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRoomIDBytes() {
      java.lang.Object ref = roomID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESIREDAIRFLOWRATE_FIELD_NUMBER = 2;
    private float desiredAirflowRate_;
    /**
     * <code>float desiredAirflowRate = 2;</code>
     */
    public float getDesiredAirflowRate() {
      return desiredAirflowRate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRoomIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, roomID_);
      }
      if (desiredAirflowRate_ != 0F) {
        output.writeFloat(2, desiredAirflowRate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRoomIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, roomID_);
      }
      if (desiredAirflowRate_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, desiredAirflowRate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof remote.Service3.AirflowRateRequest)) {
        return super.equals(obj);
      }
      remote.Service3.AirflowRateRequest other = (remote.Service3.AirflowRateRequest) obj;

      boolean result = true;
      result = result && getRoomID()
          .equals(other.getRoomID());
      result = result && (
          java.lang.Float.floatToIntBits(getDesiredAirflowRate())
          == java.lang.Float.floatToIntBits(
              other.getDesiredAirflowRate()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROOMID_FIELD_NUMBER;
      hash = (53 * hash) + getRoomID().hashCode();
      hash = (37 * hash) + DESIREDAIRFLOWRATE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDesiredAirflowRate());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static remote.Service3.AirflowRateRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static remote.Service3.AirflowRateRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static remote.Service3.AirflowRateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static remote.Service3.AirflowRateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static remote.Service3.AirflowRateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static remote.Service3.AirflowRateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static remote.Service3.AirflowRateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static remote.Service3.AirflowRateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static remote.Service3.AirflowRateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static remote.Service3.AirflowRateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static remote.Service3.AirflowRateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static remote.Service3.AirflowRateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(remote.Service3.AirflowRateRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AirflowRateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AirflowRateRequest)
        remote.Service3.AirflowRateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return remote.Service3.internal_static_AirflowRateRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return remote.Service3.internal_static_AirflowRateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                remote.Service3.AirflowRateRequest.class, remote.Service3.AirflowRateRequest.Builder.class);
      }

      // Construct using remote.Service3.AirflowRateRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        roomID_ = "";

        desiredAirflowRate_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return remote.Service3.internal_static_AirflowRateRequest_descriptor;
      }

      @java.lang.Override
      public remote.Service3.AirflowRateRequest getDefaultInstanceForType() {
        return remote.Service3.AirflowRateRequest.getDefaultInstance();
      }

      @java.lang.Override
      public remote.Service3.AirflowRateRequest build() {
        remote.Service3.AirflowRateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public remote.Service3.AirflowRateRequest buildPartial() {
        remote.Service3.AirflowRateRequest result = new remote.Service3.AirflowRateRequest(this);
        result.roomID_ = roomID_;
        result.desiredAirflowRate_ = desiredAirflowRate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof remote.Service3.AirflowRateRequest) {
          return mergeFrom((remote.Service3.AirflowRateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(remote.Service3.AirflowRateRequest other) {
        if (other == remote.Service3.AirflowRateRequest.getDefaultInstance()) return this;
        if (!other.getRoomID().isEmpty()) {
          roomID_ = other.roomID_;
          onChanged();
        }
        if (other.getDesiredAirflowRate() != 0F) {
          setDesiredAirflowRate(other.getDesiredAirflowRate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        remote.Service3.AirflowRateRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (remote.Service3.AirflowRateRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object roomID_ = "";
      /**
       * <code>string roomID = 1;</code>
       */
      public java.lang.String getRoomID() {
        java.lang.Object ref = roomID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          roomID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string roomID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRoomIDBytes() {
        java.lang.Object ref = roomID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roomID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string roomID = 1;</code>
       */
      public Builder setRoomID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roomID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string roomID = 1;</code>
       */
      public Builder clearRoomID() {
        
        roomID_ = getDefaultInstance().getRoomID();
        onChanged();
        return this;
      }
      /**
       * <code>string roomID = 1;</code>
       */
      public Builder setRoomIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roomID_ = value;
        onChanged();
        return this;
      }

      private float desiredAirflowRate_ ;
      /**
       * <code>float desiredAirflowRate = 2;</code>
       */
      public float getDesiredAirflowRate() {
        return desiredAirflowRate_;
      }
      /**
       * <code>float desiredAirflowRate = 2;</code>
       */
      public Builder setDesiredAirflowRate(float value) {
        
        desiredAirflowRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float desiredAirflowRate = 2;</code>
       */
      public Builder clearDesiredAirflowRate() {
        
        desiredAirflowRate_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AirflowRateRequest)
    }

    // @@protoc_insertion_point(class_scope:AirflowRateRequest)
    private static final remote.Service3.AirflowRateRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new remote.Service3.AirflowRateRequest();
    }

    public static remote.Service3.AirflowRateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AirflowRateRequest>
        PARSER = new com.google.protobuf.AbstractParser<AirflowRateRequest>() {
      @java.lang.Override
      public AirflowRateRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AirflowRateRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AirflowRateRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AirflowRateRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public remote.Service3.AirflowRateRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ControlResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ControlResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string status = 1;</code>
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 1;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>float currentValue = 2;</code>
     */
    float getCurrentValue();
  }
  /**
   * Protobuf type {@code ControlResponse}
   */
  public  static final class ControlResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ControlResponse)
      ControlResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ControlResponse.newBuilder() to construct.
    private ControlResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ControlResponse() {
      status_ = "";
      currentValue_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ControlResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            case 21: {

              currentValue_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return remote.Service3.internal_static_ControlResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return remote.Service3.internal_static_ControlResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              remote.Service3.ControlResponse.class, remote.Service3.ControlResponse.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private volatile java.lang.Object status_;
    /**
     * <code>string status = 1;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string status = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENTVALUE_FIELD_NUMBER = 2;
    private float currentValue_;
    /**
     * <code>float currentValue = 2;</code>
     */
    public float getCurrentValue() {
      return currentValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, status_);
      }
      if (currentValue_ != 0F) {
        output.writeFloat(2, currentValue_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, status_);
      }
      if (currentValue_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, currentValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof remote.Service3.ControlResponse)) {
        return super.equals(obj);
      }
      remote.Service3.ControlResponse other = (remote.Service3.ControlResponse) obj;

      boolean result = true;
      result = result && getStatus()
          .equals(other.getStatus());
      result = result && (
          java.lang.Float.floatToIntBits(getCurrentValue())
          == java.lang.Float.floatToIntBits(
              other.getCurrentValue()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (37 * hash) + CURRENTVALUE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCurrentValue());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static remote.Service3.ControlResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static remote.Service3.ControlResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static remote.Service3.ControlResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static remote.Service3.ControlResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static remote.Service3.ControlResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static remote.Service3.ControlResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static remote.Service3.ControlResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static remote.Service3.ControlResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static remote.Service3.ControlResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static remote.Service3.ControlResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static remote.Service3.ControlResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static remote.Service3.ControlResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(remote.Service3.ControlResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ControlResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ControlResponse)
        remote.Service3.ControlResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return remote.Service3.internal_static_ControlResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return remote.Service3.internal_static_ControlResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                remote.Service3.ControlResponse.class, remote.Service3.ControlResponse.Builder.class);
      }

      // Construct using remote.Service3.ControlResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = "";

        currentValue_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return remote.Service3.internal_static_ControlResponse_descriptor;
      }

      @java.lang.Override
      public remote.Service3.ControlResponse getDefaultInstanceForType() {
        return remote.Service3.ControlResponse.getDefaultInstance();
      }

      @java.lang.Override
      public remote.Service3.ControlResponse build() {
        remote.Service3.ControlResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public remote.Service3.ControlResponse buildPartial() {
        remote.Service3.ControlResponse result = new remote.Service3.ControlResponse(this);
        result.status_ = status_;
        result.currentValue_ = currentValue_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof remote.Service3.ControlResponse) {
          return mergeFrom((remote.Service3.ControlResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(remote.Service3.ControlResponse other) {
        if (other == remote.Service3.ControlResponse.getDefaultInstance()) return this;
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        if (other.getCurrentValue() != 0F) {
          setCurrentValue(other.getCurrentValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        remote.Service3.ControlResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (remote.Service3.ControlResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string status = 1;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status = 1;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string status = 1;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }

      private float currentValue_ ;
      /**
       * <code>float currentValue = 2;</code>
       */
      public float getCurrentValue() {
        return currentValue_;
      }
      /**
       * <code>float currentValue = 2;</code>
       */
      public Builder setCurrentValue(float value) {
        
        currentValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float currentValue = 2;</code>
       */
      public Builder clearCurrentValue() {
        
        currentValue_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ControlResponse)
    }

    // @@protoc_insertion_point(class_scope:ControlResponse)
    private static final remote.Service3.ControlResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new remote.Service3.ControlResponse();
    }

    public static remote.Service3.ControlResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ControlResponse>
        PARSER = new com.google.protobuf.AbstractParser<ControlResponse>() {
      @java.lang.Override
      public ControlResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ControlResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ControlResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ControlResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public remote.Service3.ControlResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeatingSystemRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeatingSystemRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AirflowRateRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AirflowRateRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ControlResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ControlResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Service3.proto\"B\n\024HeatingSystemRequest" +
      "\022\016\n\006roomID\030\001 \001(\t\022\032\n\022desiredTemperature\030\002" +
      " \001(\002\"@\n\022AirflowRateRequest\022\016\n\006roomID\030\001 \001" +
      "(\t\022\032\n\022desiredAirflowRate\030\002 \001(\002\"7\n\017Contro" +
      "lResponse\022\016\n\006status\030\001 \001(\t\022\024\n\014currentValu" +
      "e\030\002 \001(\0022\225\001\n\rRemoteControl\022C\n\024HeatingSyst" +
      "emControl\022\025.HeatingSystemRequest\032\020.Contr" +
      "olResponse(\0010\001\022?\n\022AirflowRateControl\022\023.A" +
      "irflowRateRequest\032\020.ControlResponse(\0010\001B" +
      "\010\n\006remoteb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HeatingSystemRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HeatingSystemRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeatingSystemRequest_descriptor,
        new java.lang.String[] { "RoomID", "DesiredTemperature", });
    internal_static_AirflowRateRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AirflowRateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AirflowRateRequest_descriptor,
        new java.lang.String[] { "RoomID", "DesiredAirflowRate", });
    internal_static_ControlResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ControlResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ControlResponse_descriptor,
        new java.lang.String[] { "Status", "CurrentValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
